<?php
/**
 * Copyright © Magmodules Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Boxplosive\Connect\Block\Adminhtml\System\Config\Button\Credentials $block
 */
?>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#boxplosive-button_credentials').click(function () {
            var params = {
                "mode":
                    jQuery("select[name='groups[api][fields][mode][value]']").val(),
                "acceptance_api_url":
                    jQuery("input[name='groups[api][fields][acceptance_api_url][value]']").val(),
                "production_api_url":
                    jQuery("input[name='groups[api][fields][production_api_url][value]']").val(),
                "acceptance_b2c_tenant_name":
                    jQuery("input[name='groups[api][fields][acceptance_b2c_tenant_name][value]']").val(),
                "production_b2c_tenant_name":
                    jQuery("input[name='groups[api][fields][production_b2c_tenant_name][value]']").val(),
                "acceptance_b2c_tenant_id":
                    jQuery("input[name='groups[api][fields][acceptance_b2c_tenant_id][value]']").val(),
                "production_b2c_tenant_id":
                    jQuery("input[name='groups[api][fields][production_b2c_tenant_id][value]']").val(),
                "tenant_id":
                    jQuery("input[name='groups[api][fields][tenant_id][value]']").val(),
                "production_client_id":
                    jQuery("input[name='groups[api][fields][production_client_id][value]']").val(),
                "production_client_secret":
                    jQuery("input[name='groups[api][fields][production_client_secret][value]']").val(),
                "acceptance_client_id":
                    jQuery("input[name='groups[api][fields][acceptance_client_id][value]']").val(),
                "acceptance_client_secret":
                    jQuery("input[name='groups[api][fields][acceptance_client_secret][value]']").val()
            };

            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.msg != 'undefined') {
                            resultText = json.msg;
                            jQuery("input[name='groups[connection][fields][account][value]']").val(json.account)
                        }
                    }

                    resultSpan.find('.result').show();
                    resultSpan[0].querySelector('.result').textContent = resultText;
                }
            });
        });
    });
</script>

<div class="check-credentials-wrapper">
    <?= $block->getButtonHtml() ?>
    <div id="result_api">
        <span class="connecting" style="display: none;">Connecting...</span>
        <span class="result"></span>
    </div>
</div>
